#pragma once

// Profile umbrella: stable Arc substrate primitives without board drivers or
// application-domain surfaces.

#include "arc/any.hpp"
#include "arc/assume.hpp"
#include "arc/audit.hpp"
#include "arc/bare_core.hpp"
#include "arc/bus.hpp"
#include "arc/cfg.hpp"
#include "arc/claim.hpp"
#include "arc/clock.hpp"
#include "arc/concepts.hpp"
#include "arc/coro.hpp"
#include "arc/fanin.hpp"
#include "arc/fence.hpp"
#include "arc/fsm.hpp"
#include "arc/init.hpp"
#include "arc/log.hpp"
#include "arc/mpsc.hpp"
#include "arc/pack.hpp"
#include "arc/plane.hpp"
#include "arc/postmortem.hpp"
#include "arc/probe.hpp"
#include "arc/rcu.hpp"
#include "arc/reg.hpp"
#include "arc/result.hpp"
#include "arc/rpc.hpp"
#include "arc/rtos.hpp"
#include "arc/sdk.hpp"
#include "arc/seq.hpp"
#include "arc/sketch.hpp"
#include "arc/soc/target.hpp"
#include "arc/spsc.hpp"
#include "arc/stack.hpp"
#include "arc/task.hpp"
#include "arc/text.hpp"
#include "arc/tight.hpp"
#include "arc/topology.hpp"
#include "arc/watch.hpp"
#include "arc/wave.hpp"
