#pragma once

#include "esp_attr.h"

#define ARC_HOT IRAM_ATTR
#define ARC_FORCE_HOT FORCE_IRAM_ATTR
#define ARC_DRAM DRAM_ATTR
#define ARC_DMA DMA_ATTR
#define ARC_DMA_ALIGN DRAM_DMA_ALIGNED_ATTR
#define ARC_RTC RTC_DATA_ATTR
#define ARC_RTC_NOINIT RTC_NOINIT_ATTR
#define ARC_RTC_CODE RTC_IRAM_ATTR
#define ARC_EXT_BSS EXT_RAM_BSS_ATTR
#define ARC_EXT_NOINIT EXT_RAM_NOINIT_ATTR
#define ARC_NOINIT __NOINIT_ATTR
