#pragma once

#if defined(ARC_TARGET_ESP32S31)
#define SOC_HOST_FAST_GPIO 0
#define SOC_HOST_AHB_DMA 0
#define SOC_HOST_SIMD 1
#define SOC_HOST_TOUCH 0
#define SOC_HOST_TOUCH_MAX_CHAN_ID 0
#else
#define SOC_HOST_FAST_GPIO 1
#define SOC_HOST_AHB_DMA 1
#define SOC_HOST_SIMD 1
#define SOC_HOST_TOUCH 1
#define SOC_HOST_TOUCH_MAX_CHAN_ID 14
#endif

#define SOC_CPU_CORES_NUM 2
#define SOC_HP_CPU_HAS_MULTIPLE_CORES 1
#define SOC_CPU_HAS_FPU 1
#define SOC_SIMD_INSTRUCTION_SUPPORTED SOC_HOST_SIMD

#define SOC_WIFI_SUPPORTED 1
#define SOC_BT_SUPPORTED 1
#define SOC_BLE_SUPPORTED 1
#define SOC_BLE_50_SUPPORTED 1
#define SOC_BLE_MESH_SUPPORTED 1
#define SOC_BLE_DEVICE_PRIVACY_SUPPORTED 1
#define SOC_ETM_SUPPORTED 1

#define SOC_DEDICATED_GPIO_SUPPORTED SOC_HOST_FAST_GPIO
#define SOC_ASYNC_MEMCPY_SUPPORTED 1
#define SOC_GDMA_SUPPORTED SOC_HOST_AHB_DMA
#define SOC_AHB_GDMA_SUPPORTED SOC_HOST_AHB_DMA
#define SOC_PSRAM_DMA_CAPABLE 1

#define SOC_ADC_SUPPORTED 1
#define SOC_ADC_DMA_SUPPORTED 1
#define SOC_I2C_SUPPORTED 1
#define SOC_I2S_SUPPORTED 1
#define SOC_GPSPI_SUPPORTED 1
#define SOC_LEDC_SUPPORTED 1
#define SOC_LCD_I80_SUPPORTED 1
#define SOC_LCD_RGB_SUPPORTED 1
#define SOC_LCDCAM_CAM_SUPPORTED 1
#define SOC_MCPWM_SUPPORTED 1
#define SOC_PCNT_SUPPORTED 1
#define SOC_RMT_SUPPORTED 1
#define SOC_RMT_SUPPORT_DMA 1
#define SOC_SDM_SUPPORTED 1
#define SOC_GPTIMER_SUPPORTED 1
#define SOC_TWAI_SUPPORTED 1
#define SOC_TEMP_SENSOR_SUPPORTED 1
#define SOC_TOUCH_SENSOR_SUPPORTED SOC_HOST_TOUCH
#define SOC_UART_SUPPORTED 1
#define SOC_USB_OTG_SUPPORTED 1
#define SOC_USB_SERIAL_JTAG_SUPPORTED 1
#define SOC_SDMMC_HOST_SUPPORTED 1

#define SOC_RNG_SUPPORTED 1
#define SOC_AES_SUPPORTED 1
#define SOC_AES_SUPPORT_DMA 1
#define SOC_AES_SUPPORT_AES_128 1
#define SOC_AES_SUPPORT_AES_256 1
#define SOC_SHA_SUPPORTED 1
#define SOC_SHA_SUPPORT_DMA 1
#define SOC_SHA_SUPPORT_SHA1 1
#define SOC_SHA_SUPPORT_SHA224 1
#define SOC_SHA_SUPPORT_SHA256 1
#define SOC_SHA_SUPPORT_SHA384 1
#define SOC_SHA_SUPPORT_SHA512 1
#define SOC_SHA_SUPPORT_SHA512_224 1
#define SOC_SHA_SUPPORT_SHA512_256 1
#define SOC_SHA_SUPPORT_SHA512_T 1
#define SOC_MPI_SUPPORTED 0
#define SOC_HMAC_SUPPORTED 1
#define SOC_DIG_SIGN_SUPPORTED 1
#define SOC_ECDSA_SUPPORTED 1

#define SOC_EFUSE_SUPPORTED 1
#define SOC_FLASH_ENCRYPTION_XTS_AES 1
#define SOC_FLASH_ENCRYPTION_XTS_AES_128 1
#define SOC_FLASH_ENCRYPTION_XTS_AES_256 1
#define SOC_SYSTIMER_SUPPORTED 1
#define SOC_WDT_SUPPORTED 1
#define SOC_XT_WDT_SUPPORTED 1

#define SOC_LIGHT_SLEEP_SUPPORTED 1
#define SOC_DEEP_SLEEP_SUPPORTED 1
#define SOC_ULP_SUPPORTED 1
#define SOC_ULP_FSM_SUPPORTED 1
#define SOC_RISCV_COPROC_SUPPORTED 1
#define SOC_RTC_FAST_MEM_SUPPORTED 1
#define SOC_RTC_SLOW_MEM_SUPPORTED 1
#define SOC_RTCIO_PIN_COUNT 22
#define SOC_RTCIO_INPUT_OUTPUT_SUPPORTED 1
#define SOC_RTCIO_HOLD_SUPPORTED 1
#define SOC_RTCIO_WAKE_SUPPORTED 1

#define SOC_CPU_INTR_NUM 32
#define SOC_GPIO_PIN_COUNT 64
#define SOC_GPIO_IN_RANGE_MAX 61
#define SOC_GPIO_OUT_RANGE_MAX 61
#define SOC_ADC_PERIPH_NUM 2
#define SOC_ADC_MAX_CHANNEL_NUM 10
#define SOC_ADC_PATT_LEN_MAX 24
#define SOC_ADC_DIGI_MAX_BITWIDTH 12
#define SOC_I2C_NUM 2
#define SOC_LEDC_TIMER_NUM 4
#define SOC_LEDC_CHANNEL_NUM 8
#define SOC_RMT_MEM_WORDS_PER_CHANNEL 48
#define SOC_SPI_PERIPH_NUM 3
#define SOC_SPI_MAX_CS_NUM 6
#define SOC_SPI_MAXIMUM_BUFFER_SIZE 64
#define SOC_SYSTIMER_COUNTER_NUM 2
#define SOC_SYSTIMER_ALARM_NUM 3
#define SOC_RSA_MAX_BIT_LEN 4096
#define SOC_DS_SIGNATURE_MAX_BIT_LEN 4096
#define SOC_DS_KEY_PARAM_MD_IV_LENGTH 16
#define SOC_DS_KEY_CHECK_MAX_WAIT_US 1100
#define SOC_FLASH_ENCRYPTED_XTS_AES_BLOCK_MAX 64
#define SOC_MPI_MEM_BLOCKS_NUM 4
#define SOC_MPI_OPERATIONS_NUM 3
#define SOC_TWAI_CONTROLLER_NUM 1
#define SOC_UART_NUM 3
#define SOC_UART_BITRATE_MAX 5000000
#define SOC_SDMMC_NUM_SLOTS 2
#define SOC_SDMMC_DATA_WIDTH_MAX 4
#define SOC_TOUCH_MAX_CHAN_ID SOC_HOST_TOUCH_MAX_CHAN_ID
