function(arc_requires out)
    set(result arc)

    foreach(feature IN LISTS ARGN)
        if(feature STREQUAL "core")
        elseif(feature STREQUAL "adc")
            list(APPEND result esp_adc)
        elseif(feature STREQUAL "cam")
            list(APPEND result esp_driver_cam)
        elseif(feature STREQUAL "copy")
            list(APPEND result esp_driver_dma)
        elseif(feature STREQUAL "gpio")
            list(APPEND result esp_driver_gpio)
        elseif(feature STREQUAL "gptimer")
            list(APPEND result esp_driver_gptimer)
        elseif(feature STREQUAL "i2s")
            list(APPEND result esp_driver_i2s)
        elseif(feature STREQUAL "lcd")
            list(APPEND result esp_lcd)
        elseif(feature STREQUAL "ledc")
            list(APPEND result esp_driver_ledc)
        elseif(feature STREQUAL "mcpwm")
            list(APPEND result esp_driver_mcpwm)
        elseif(feature STREQUAL "net")
            list(APPEND result esp_event esp_netif esp_wifi nvs_flash)
        elseif(feature STREQUAL "ota")
            list(APPEND result app_update esp_partition)
        elseif(feature STREQUAL "pcnt")
            list(APPEND result esp_driver_pcnt)
        elseif(feature STREQUAL "rmt")
            list(APPEND result esp_driver_rmt)
        elseif(feature STREQUAL "sdm")
            list(APPEND result esp_driver_sdm)
        elseif(feature STREQUAL "space")
            list(APPEND result app_update bootloader_support esp_partition spi_flash)
        elseif(feature STREQUAL "spi")
            list(APPEND result esp_driver_spi)
        elseif(feature STREQUAL "store")
            list(APPEND result nvs_flash)
        elseif(feature STREQUAL "temp")
            list(APPEND result esp_driver_tsens)
        elseif(feature STREQUAL "twai")
            list(APPEND result esp_driver_twai)
        elseif(feature STREQUAL "udp")
            list(APPEND result esp_event esp_netif esp_wifi lwip nvs_flash)
        elseif(feature STREQUAL "espnow")
            list(APPEND result esp_event esp_netif esp_wifi nvs_flash)
        else()
            message(FATAL_ERROR "Unknown Arc feature '${feature}'")
        endif()
    endforeach()

    list(REMOVE_DUPLICATES result)
    set(${out} "${result}" PARENT_SCOPE)
endfunction()
