function(arc_requires out)
    set(result arc)

    foreach(feature IN LISTS ARGN)
        if(feature STREQUAL "core")
        elseif(feature STREQUAL "acoustic_slam")
            list(APPEND result esp_driver_i2s esp_driver_ledc)
        elseif(feature STREQUAL "adc")
            list(APPEND result esp_adc)
        elseif(feature STREQUAL "aes")
            list(APPEND result mbedtls)
        elseif(feature STREQUAL "ble")
            list(APPEND result bt nvs_flash)
        elseif(feature STREQUAL "blackbox")
            list(APPEND result esp_partition spi_flash)
        elseif(feature STREQUAL "cam")
            list(APPEND result esp_driver_cam)
        elseif(feature STREQUAL "chaos")
            list(APPEND result esp_driver_gpio esp_driver_i2c esp_wifi)
        elseif(feature STREQUAL "covert")
            list(APPEND result esp_driver_ledc esp_driver_sdm)
        elseif(feature STREQUAL "cloak")
        elseif(feature STREQUAL "copy")
            list(APPEND result esp_driver_dma)
        elseif(feature STREQUAL "csi")
            list(APPEND result esp_event esp_netif esp_wifi nvs_flash)
        elseif(feature STREQUAL "digital_twin")
            list(APPEND result esp_driver_mcpwm esp_driver_rmt)
        elseif(feature STREQUAL "eap")
            list(APPEND result esp_event esp_netif esp_wifi nvs_flash wpa_supplicant)
        elseif(feature STREQUAL "etm")
            list(APPEND result esp_hw_support)
        elseif(feature STREQUAL "fabric")
            list(APPEND result esp_event esp_netif esp_wifi nvs_flash)
        elseif(feature STREQUAL "flexroute")
            list(APPEND result esp_driver_gpio)
        elseif(feature STREQUAL "gpio")
            list(APPEND result esp_driver_gpio)
        elseif(feature STREQUAL "gptimer")
            list(APPEND result esp_driver_gptimer)
        elseif(feature STREQUAL "hmac")
            list(APPEND result esp_security)
        elseif(feature STREQUAL "hotpatch")
        elseif(feature STREQUAL "hypervisor")
            list(APPEND result esp_system hal soc)
        elseif(feature STREQUAL "http")
            list(APPEND result esp_http_client)
        elseif(feature STREQUAL "i2c")
            list(APPEND result esp_driver_i2c)
        elseif(feature STREQUAL "i2s")
            list(APPEND result esp_driver_i2s)
        elseif(feature STREQUAL "intermittent")
            list(APPEND result esp_system)
        elseif(feature STREQUAL "jit")
            list(APPEND result esp_system)
        elseif(feature STREQUAL "kyber")
        elseif(feature STREQUAL "lcd")
            list(APPEND result esp_lcd)
        elseif(feature STREQUAL "ledc")
            list(APPEND result esp_driver_ledc)
        elseif(feature STREQUAL "lifi")
            list(APPEND result esp_driver_mcpwm esp_driver_rmt esp_hw_support)
        elseif(feature STREQUAL "maglev")
            list(APPEND result esp_adc esp_driver_mcpwm)
        elseif(feature STREQUAL "mcpwm")
            list(APPEND result esp_driver_mcpwm)
        elseif(feature STREQUAL "mdns")
            list(APPEND result esp_event esp_netif esp_wifi lwip nvs_flash)
        elseif(feature STREQUAL "mpi")
            list(APPEND result mbedtls)
        elseif(feature STREQUAL "nav")
        elseif(feature STREQUAL "net")
            list(APPEND result esp_event esp_netif esp_wifi nvs_flash)
        elseif(feature STREQUAL "ota")
            list(APPEND result app_update esp_partition)
        elseif(feature STREQUAL "otg")
            list(APPEND result esp_hw_support)
        elseif(feature STREQUAL "paillier")
            list(APPEND result mbedtls)
        elseif(feature STREQUAL "puf")
            list(APPEND result esp_adc mbedtls)
        elseif(feature STREQUAL "pm")
            list(APPEND result esp_pm)
        elseif(feature STREQUAL "pcnt")
            list(APPEND result esp_driver_pcnt)
        elseif(feature STREQUAL "poll")
            list(APPEND result lwip)
        elseif(feature STREQUAL "rng")
        elseif(feature STREQUAL "rtc")
            list(APPEND result esp_driver_gpio)
        elseif(feature STREQUAL "rdma")
            list(APPEND result esp_event esp_netif esp_wifi nvs_flash)
        elseif(feature STREQUAL "rmt")
            list(APPEND result esp_driver_rmt)
        elseif(feature STREQUAL "sdm")
            list(APPEND result esp_driver_sdm)
        elseif(feature STREQUAL "sdr")
            list(APPEND result esp_driver_cam esp_driver_gpio)
        elseif(feature STREQUAL "star_tracker")
            list(APPEND result esp_driver_cam)
        elseif(feature STREQUAL "sha")
            list(APPEND result mbedtls)
        elseif(feature STREQUAL "sign")
            list(APPEND result esp_security)
        elseif(feature STREQUAL "space")
            list(APPEND result app_update bootloader_support esp_partition spi_flash)
        elseif(feature STREQUAL "snn")
        elseif(feature STREQUAL "spi")
            list(APPEND result esp_driver_spi)
        elseif(feature STREQUAL "store")
            list(APPEND result nvs_flash)
        elseif(feature STREQUAL "temp")
            list(APPEND result esp_driver_tsens)
        elseif(feature STREQUAL "touch")
            list(APPEND result esp_driver_touch_sens)
        elseif(feature STREQUAL "twai")
            list(APPEND result esp_driver_twai)
        elseif(feature STREQUAL "udp")
            list(APPEND result esp_event esp_netif esp_wifi lwip nvs_flash)
        elseif(feature STREQUAL "uart")
            list(APPEND result esp_driver_uart)
        elseif(feature STREQUAL "ulp")
            list(APPEND result ulp)
        elseif(feature STREQUAL "ulp_ml")
            list(APPEND result ulp)
        elseif(feature STREQUAL "espnow")
            list(APPEND result esp_event esp_netif esp_wifi nvs_flash)
        elseif(feature STREQUAL "usb_host")
            list(APPEND result esp_hal_usb)
        elseif(feature STREQUAL "fuse")
            list(APPEND result efuse)
        elseif(feature STREQUAL "fs")
            list(APPEND result esp_partition fatfs spiffs vfs wear_levelling)
        elseif(feature STREQUAL "sd")
            list(APPEND result esp_driver_sdmmc fatfs sdmmc vfs)
        elseif(feature STREQUAL "tcp")
            list(APPEND result lwip)
        elseif(feature STREQUAL "tls")
            list(APPEND result esp-tls lwip)
        elseif(feature STREQUAL "time")
            list(APPEND result esp_timer)
        elseif(feature STREQUAL "trax")
            list(APPEND result esp_hw_support esp_system hal soc xtensa)
        elseif(feature STREQUAL "usb")
            list(APPEND result esp_driver_usb_serial_jtag)
        elseif(feature STREQUAL "wdt")
            list(APPEND result esp_system)
        elseif(feature STREQUAL "wavefront")
            list(APPEND result esp_driver_i2s)
        elseif(feature STREQUAL "xts")
            list(APPEND result esp_partition spi_flash)
        else()
            message(FATAL_ERROR "Unknown Arc feature '${feature}'")
        endif()
    endforeach()

    list(REMOVE_DUPLICATES result)
    set(${out} "${result}" PARENT_SCOPE)
endfunction()
